theme: minima
title: "Gama-CommuteCast"
description: "Aplikasi tracker bus dan informasi kondisi lingkungan di sekitar UGM."https://github.com/ahmadzaki2975/Gama-CommuteCast/edit/main/_config.yml
exclude: ['README.md']
